apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value }}
    {{- end}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.deployment.matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end}}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value }}
        {{- end}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mnt
              mountPath: /usr/share/nginx/html/index.html
              subPath: file
      volumes:
        - name: mnt
          configMap:
            name: nginx-cfgmap
      nodeSelector:
        node: affinity
